---
- name: Prepare
  hosts: all
  pre_tasks:
    # Set a flag to skip chrony operations for Alpine since Github CI has major issues
    # running them that I cannot replicate
    - set_fact:
        __molecule_ci: true

    - include_role:
        name: asymworks.baseline
        tasks_from: pre-tasks.yaml

    # Override the Alpine Diskless Mode fact since the docker container will
    # not show a mount point for '/'
    - when: ansible_facts['os_family']|lower == 'alpine'
      set_fact:
        alpine_diskless: false

  roles:
    - asymworks.baseline

  tasks:
    - name: Ensure /var/log/auth.log exists for Debian 9
      when: telegraf_enabled and ansible_facts['os_family']|lower == 'debian'
      file:
        path: /var/log/auth.log
        state: touch

  post_tasks:
    - include_role:
        name: asymworks.baseline
        tasks_from: post-tasks.yaml

  vars:
    asset_name: molecule-container
    asset_tag: c:molecule:01
